@ Generated by Synth WASM Compiler
@ Target: ARM Cortex-M

.syntax unified
.thumb
.text

.global synth_add
.type synth_add, %function
synth_add:
    @ Function prologue
    push {r4, lr}

    @ WASM function body
    add r0, r0, r1

    @ Function epilogue
    pop {r4, pc}
.size synth_add, .-synth_add