@ Generated by Synth WASM Compiler
@ Source: calculator.wat
@ Target: ARM Cortex-M (Thumb-2)
@
@ 14 exported functions: add, sub, mul, div_safe,
@   acc_set, acc_get, acc_add,
@   bit_and, bit_or, bit_xor, bit_not,
@   max, min, abs
@
@ Register convention (AAPCS):
@   R0-R3: arguments / scratch
@   R0: return value
@   R4-R11: callee-saved
@   LR (R14): return address

.syntax unified
.thumb
.text

@ ---------------------------------------------------------------
@ Basic arithmetic
@ ---------------------------------------------------------------

@ add(a, b) -> a + b
.global synth_add
.type synth_add, %function
.thumb_func
synth_add:
    adds r0, r0, r1
    bx   lr
.size synth_add, .-synth_add

@ sub(a, b) -> a - b
.global synth_sub
.type synth_sub, %function
.thumb_func
synth_sub:
    subs r0, r0, r1
    bx   lr
.size synth_sub, .-synth_sub

@ mul(a, b) -> a * b
.global synth_mul
.type synth_mul, %function
.thumb_func
synth_mul:
    muls r0, r1, r0
    bx   lr
.size synth_mul, .-synth_mul

@ div_safe(a, b) -> a / b, returns 0 when b == 0
.global synth_div_safe
.type synth_div_safe, %function
.thumb_func
synth_div_safe:
    cmp  r1, #0
    beq  .Ldiv_zero
    sdiv r0, r0, r1
    bx   lr
.Ldiv_zero:
    movs r0, #0
    bx   lr
.size synth_div_safe, .-synth_div_safe

@ ---------------------------------------------------------------
@ Accumulator operations (use static memory word)
@ ---------------------------------------------------------------

@ acc_set(v) -- store v to accumulator
.global synth_acc_set
.type synth_acc_set, %function
.thumb_func
synth_acc_set:
    ldr  r1, =synth_accumulator
    str  r0, [r1]
    bx   lr
.size synth_acc_set, .-synth_acc_set

@ acc_get() -> current accumulator value
.global synth_acc_get
.type synth_acc_get, %function
.thumb_func
synth_acc_get:
    ldr  r0, =synth_accumulator
    ldr  r0, [r0]
    bx   lr
.size synth_acc_get, .-synth_acc_get

@ acc_add(v) -> acc += v, return new value
.global synth_acc_add
.type synth_acc_add, %function
.thumb_func
synth_acc_add:
    ldr  r1, =synth_accumulator
    ldr  r2, [r1]
    adds r0, r2, r0
    str  r0, [r1]
    bx   lr
.size synth_acc_add, .-synth_acc_add

@ ---------------------------------------------------------------
@ Bitwise operations
@ ---------------------------------------------------------------

@ bit_and(a, b) -> a & b
.global synth_bit_and
.type synth_bit_and, %function
.thumb_func
synth_bit_and:
    ands r0, r0, r1
    bx   lr
.size synth_bit_and, .-synth_bit_and

@ bit_or(a, b) -> a | b
.global synth_bit_or
.type synth_bit_or, %function
.thumb_func
synth_bit_or:
    orrs r0, r0, r1
    bx   lr
.size synth_bit_or, .-synth_bit_or

@ bit_xor(a, b) -> a ^ b
.global synth_bit_xor
.type synth_bit_xor, %function
.thumb_func
synth_bit_xor:
    eors r0, r0, r1
    bx   lr
.size synth_bit_xor, .-synth_bit_xor

@ bit_not(a) -> ~a
.global synth_bit_not
.type synth_bit_not, %function
.thumb_func
synth_bit_not:
    mvns r0, r0
    bx   lr
.size synth_bit_not, .-synth_bit_not

@ ---------------------------------------------------------------
@ Comparison / selection
@ ---------------------------------------------------------------

@ max(a, b) -> larger value (signed)
.global synth_max
.type synth_max, %function
.thumb_func
synth_max:
    cmp  r0, r1
    bge  .Lmax_done
    mov  r0, r1
.Lmax_done:
    bx   lr
.size synth_max, .-synth_max

@ min(a, b) -> smaller value (signed)
.global synth_min
.type synth_min, %function
.thumb_func
synth_min:
    cmp  r0, r1
    ble  .Lmin_done
    mov  r0, r1
.Lmin_done:
    bx   lr
.size synth_min, .-synth_min

@ abs(x) -> |x|
.global synth_abs
.type synth_abs, %function
.thumb_func
synth_abs:
    cmp  r0, #0
    bge  .Labs_done
    rsbs r0, r0, #0
.Labs_done:
    bx   lr
.size synth_abs, .-synth_abs

@ ---------------------------------------------------------------
@ BSS: accumulator storage (WASM linear memory word 0)
@ ---------------------------------------------------------------
.bss
.align 4
.global synth_accumulator
synth_accumulator:
    .space 4
