#!/usr/bin/env python3
"""Generator for scripts/repro/vfp_local_pressure_1069.wat (#1069 increment 2).

Regenerate with:  python3 scripts/repro/gen_vfp_local_1069.py > scripts/repro/vfp_local_pressure_1069.wat
The checked-in .wat is the fixture of record; this generator documents its shape.
"""

HEADER = """;; #1069 (RQ-60-VFPPRESSURE increment 2) — VFP pressure from HOMED LOCALS,
;; not operand-stack depth. jess's falcon measurement (fixture credit: jess):
;;
;;     LOCALS (homed)             OPERAND STACK (#881-rescued)
;;       13 locals : ok             30 deep : ok
;;       14 locals : EXHAUSTED      60 deep : ok
;;
;; Sixty simultaneously-live f32 on the operand stack compile (the #881 spill
;; rung rescues them); fourteen in homed locals do not — a home S-register is
;; pinned for the function's extent and the #881 victim search explicitly
;; skips homes. So the 13->14 wall is HOME residence, not register-file
;; capacity, and extending the pool into callee-saved S16..S31 would only
;; move the same wall outward.
;;
;;  * live13  — jess's NEGATIVE CONTROL: must keep compiling (base path,
;;              byte-identical by construction — the rung never fires).
;;  * live14  — the red line: param home S0 + 14 pinned local homes + tree
;;              temps > 16 S-registers. Fails on cortex-m7dp before the fix.
;;  * live16  — same wall, further in (jess measured 16 exhausted too).
;;  * live24  — 24 homed locals: forces MORE frame-resident locals than the
;;              default 8-slot spill pool holds, so the fix's slot demand
;;              composes with the #587 pool-grow retry INSIDE the VFP rung
;;              (this is the test that the reworded slot-exhaustion message
;;              still triggers the grow — the substring IS control flow).
;;  * live8d  — the f64 twin on m7dp: param home D0 + 8 pinned D homes
;;              exhausts the caller-saved D0..D7 pair file.
;;
;; Every local is derived from the param (nothing constant-folds) and all are
;; consumed in ONE product tree, mirroring the falcon control-math shape
;; (attitude@0.7.0#tick / ekf@0.7.0#estimate, both phase-1 S exhaustion).
;;
;; GENERATED by scripts/repro/gen_vfp_local_1069.py — edit there, regenerate.
"""


def live(name: str, n: int, ty: str) -> str:
    lines = [f'  (func ${name} (export "{name}") (param $a {ty}) (result {ty})']
    lines.append("    (local " + " ".join([ty] * n) + ")")
    for k in range(1, n + 1):
        lines.append(f"    (local.set {k} ({ty}.mul (local.get 0) ({ty}.const {k}.5)))")
    expr = "(local.get 1)"
    for k in range(2, n + 1):
        expr = f"({ty}.mul {expr} (local.get {k}))"
    lines.append(f"    {expr})")
    return "\n".join(lines)


if __name__ == "__main__":
    print(HEADER)
    print("(module")
    print(live("live13", 13, "f32"))
    print(live("live14", 14, "f32"))
    print(live("live16", 16, "f32"))
    print(live("live24", 24, "f32"))
    print(live("live8d", 8, "f64"))
    print(")")
