#!/usr/bin/env python3
# ci-status: wired
# ci-checks: stdout /^gen-islandpass: ([0-9]+) fixture\(s\) match the generator$/ >= 2
"""RQ-74-ISLANDREACH (#1331): generate the spanning-branch island fixtures.

WHY THIS FILE EXISTS AT ALL. `islandpass_1331_spanning.wat` carries the header
"Generated by scripts/repro/gen_islandpass_1331.py" and that script was NEVER
COMMITTED — `git log --all --diff-filter=A -- '*gen_islandpass*'` matches
nothing, on any ref, ever. So the one fixture the #1331 execution differential
runs cited a provenance that did not exist, and no variant of it could be
produced without hand-writing 1200 lines of WAT.

WHAT THIS DOES NOT CLAIM. It does not reproduce the v0.73 fixture byte for byte.
That fixture's real generator is gone, so `islandpass_1331_spanning.wat` stays
exactly as it shipped and is NOT regenerated here — rewriting a pinned fixture to
match a reconstructed generator would move bytes an oracle is pinned on, to make
a provenance claim true after the fact. The variants below are NEW, and their
provenance is this file.

THE SHAPE, and why each part is load-bearing (inherited from the v0.73 fixture):
  * a 4 KB+ function, so the literal pool cannot be reached inline and an island
    must be placed;
  * literals loaded BEFORE, INSIDE and AFTER the spanned region, so a pool patch
    landing in the wrong pool is observable rather than degenerate;
  * a direct CALL inside the spanned region, so the stream carries an
    R_ARM_THM_CALL whose offset is recorded from code.len();
  * a branch that SPANS the island placement point — the thing v0.72 refused and
    v0.73 made work.

WHAT v0.74 ADDS: the span DIRECTION and NESTING are now varied. v0.73 covered a
single forward `br_if` out of one block. A backward branch (loop latch) and a
branch out of a nested block place the island on the other side of the target
and at a different depth, and neither shape had any coverage.

Usage:  python3 scripts/repro/gen_islandpass_1331.py [--check]
        --check regenerates into memory and diffs against the committed files,
        so a fixture edited by hand without touching this generator is caught.
"""
import argparse
import os
import sys

REPRO = os.path.dirname(os.path.abspath(__file__))

# Enough i64 multiply chains to push the function past the 4095-byte imm12
# reach. Measured, not guessed: see --check output for each fixture's size.
PAD_MULS = 170


def _pad(n: int) -> list[str]:
    """The bulk. Each block is 4 instructions and moves `local 2`."""
    out = []
    for i in range(n):
        out += ["      local.get 2",
                # ODD multipliers only. With even factors the 170-deep chain
                # drives the low 32 bits to a fixed point, `i32.wrap_i64`
                # returns the same value for every argument, and the
                # differential can no longer see an argument-dropping
                # miscompile. Measured: even factors gave 1 distinct result
                # across 5 args; odd factors give 5.
                f"      i64.const {3 + 2 * (i % 6)}",
                "      i64.mul",
                "      local.set 2"]
    return out


def _preamble(name: str, kind: str) -> list[str]:
    return [
        "(module",
        f"  ;; RQ-74-ISLANDREACH (#1331). Generated by scripts/repro/gen_islandpass_1331.py.",
        f"  ;; shape: {kind}",
        "  ;;",
        "  ;; A 4 KB+ function whose literal pool needs an inline island, with a",
        f"  ;; {kind} branch that SPANS the island placement point, a direct CALL",
        "  ;; inside the spanned region, and three distinct static-data literals",
        "  ;; loaded before / inside / after the span.",
        "  (memory 1)",
        '  (data (i32.const 1024) "islandreach-A")',
        '  (data (i32.const 2048) "islandreach-B")',
        '  (data (i32.const 3072) "islandreach-C")',
        "",
        "  (func $helper (param i32) (result i32)",
        "    local.get 0",
        "    i32.const 3",
        "    i32.mul",
        "    i32.const 7",
        "    i32.add",
        "  )",
        "",
    ]


def backward(name: str) -> str:
    """A LOOP latch: the branch target is BEHIND the branch, so the island lands
    between the target and the branch rather than between the branch and a
    forward target. v0.73 had no coverage of this direction."""
    L = _preamble(name, "backward (loop latch)")
    L += [
        f'  (func $big (export "big") (param i32) (result i32)',
        "    (local i32) (local i64) (local i32) (local i32)",
        "    ;; seed the i64 accumulator FROM THE PARAM, so the emitted code's",
        "    ;; result varies per argument — an execution differential whose",
        "    ;; expected values are constant cannot see an argument-dropping",
        "    ;; miscompile.",
        "    local.get 0",
        "    i64.extend_i32_u",
        "    i64.const 1",
        "    i64.or",
        "    local.set 2",
        "    ;; literal 1 — loaded BEFORE the loop opens",
        "    i32.const 1024",
        "    i32.load",
        "    local.set 1",
        "    (loop $L",
        "      ;; a direct call INSIDE the spanned region",
        "      local.get 1",
        "      call $helper",
        "      local.set 3",
        "      ;; literal 2, also inside the span",
        "      i32.const 2048",
        "      i32.load",
        "      local.get 3",
        "      i32.add",
        "      local.set 3",
    ]
    L += _pad(PAD_MULS)
    L += [
        "      ;; the LATCH: a backward branch spanning the island placement",
        "      local.get 4",
        "      i32.const 1",
        "      i32.add",
        "      local.tee 4",
        "      ;; trip count is MASKED to 0..3. An unbounded `i < param` loop",
        "      ;; makes big(0x7FFFFFFF) ~2^31 iterations: wasmtime runs that",
        "      ;; natively in seconds, the unicorn harness does not, and the",
        "      ;; differential then reports a MISCOMPILE that is really an",
        "      ;; emulation budget. Measured: that exact false positive appeared",
        "      ;; on this fixture before the mask.",
        "      local.get 0",
        "      i32.const 3",
        "      i32.and",
        "      i32.lt_u",
        "      br_if $L",
        "    )",
        "    ;; literal 3 — after the span closes, so its pool must still resolve",
        "    i32.const 3072",
        "    i32.load",
        "    local.get 1",
        "    i32.add",
        "    local.get 3",
        "    i32.add",
        "    local.get 2",
        "    i32.wrap_i64",
        "    i32.add",
        "  )",
        ")",
    ]
    return "\n".join(L) + "\n"


def nested(name: str) -> str:
    """A branch out of a NESTED block (`br 1`), so the island is placed at a
    different block depth than the single-level `br_if 0` v0.73 covered."""
    L = _preamble(name, "nested (br 1 out of an inner block)")
    L += [
        f'  (func $big (export "big") (param i32) (result i32)',
        "    (local i32) (local i64) (local i32)",
        "    (block",
        "      (block",
        "        ;; seed the i64 accumulator FROM THE PARAM (see backward()).",
        "        local.get 0",
        "        i64.extend_i32_u",
        "        i64.const 1",
        "        i64.or",
        "        local.set 2",
        "        ;; literal 1 — loaded BEFORE the span opens",
        "        i32.const 1024",
        "        i32.load",
        "        local.set 1",
        "        ;; the branch that SPANS the island, out of TWO blocks",
        "        local.get 0",
        "        br_if 1",
        "        ;; a direct call INSIDE the spanned region",
        "        local.get 1",
        "        call $helper",
        "        local.set 3",
        "        ;; literal 2, also inside the span",
        "        i32.const 2048",
        "        i32.load",
        "        local.get 3",
        "        i32.add",
        "        local.set 3",
    ]
    L += ["  " + s.strip().rjust(len(s.strip()) + 8) for s in _pad(PAD_MULS)]
    L += [
        "      )",
        "    )",
        "    ;; literal 3 — after the span closes, so its pool must still resolve",
        "    i32.const 3072",
        "    i32.load",
        "    local.get 1",
        "    i32.add",
        "    local.get 3",
        "    i32.add",
        "    local.get 2",
        "    i32.wrap_i64",
        "    i32.add",
        "  )",
        ")",
    ]
    return "\n".join(L) + "\n"


FIXTURES = {
    "islandpass_1331_backspan.wat": backward,
    "islandpass_1331_nested.wat": nested,
}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="diff the generated text against the committed files")
    args = ap.parse_args()
    bad = []
    ok = 0
    for fn, fn_gen in FIXTURES.items():
        path = os.path.join(REPRO, fn)
        text = fn_gen(fn)
        if args.check:
            if not os.path.isfile(path):
                bad.append(f"{fn}: MISSING — run this generator without --check")
                continue
            have = open(path).read()
            if have != text:
                bad.append(f"{fn}: DIFFERS from the generator's output "
                           f"({len(have)} bytes on disk, {len(text)} generated) "
                           f"— a fixture was hand-edited without the generator")
            else:
                ok += 1
                print(f"  ok  {fn} ({len(text)} bytes, {text.count(chr(10))} lines)")
        else:
            open(path, "w").write(text)
            print(f"  wrote {fn} ({len(text)} bytes)")
    if args.check:
        # The POPULATION line. The verdict already reds via the exit code, and an
        # exit code cannot see a run that checked NOTHING — a generator whose
        # FIXTURES dict lost an entry would pass silently.
        print(f"gen-islandpass: {ok} fixture(s) match the generator")
    if bad:
        for b in bad:
            print(f"FAIL {b}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
