#!/usr/bin/env python3
# ci-status: wired
# ci-checks: emulations >= 1629
"""RQ-65-ALIASCLASS (#1189) — the home-register alias class, executed per
consumer family on all four legs.

THE MECHANISM. `local.get` of a register-homed local pushes THE HOME
REGISTER uncopied. #677 (bulk-memory pointer walk), #989 (get→set→use) and
#1189 (if/else join) were three consumers that wrote it, each a silent wrong
answer. The static half of this artifact (`synth_synthesis::home_alias`, run
over the corpus by `home_alias_audit_corpus_1189.py`) proves no emitted
instruction of the ARM direct selector writes a live home. THIS half asks
the same question by EXECUTION, per consumer family, on every leg — because
the static audit covers exactly one selector (the ARM direct one) and the
other three legs alias too:

  arm-reloc   direct selector `select_with_stack` (#197): params r0–r3 and
              promoted locals r4–r8 pushed uncopied — the audited leg.
  arm-self    the OPTIMIZED selector for these straight-line shapes:
              `ir_to_arm` maps a `local.get`'s vreg straight onto the param
              register (no copy either); shapes it declines fall to the
              direct selector.
  rv32-reloc  params are COPIED on `local.get` (`mv dst, a_n`) — a promoted
              local (`s8..s10`, #472) is aliased uncopied.
  aarch64     a leaf function that never writes a param pushes the AAPCS64
              register itself (`stack.push(params[i])`).

Every function feeds params homed in r0..r3 (or, in `promo`, a local the
selectors promote) to ONE consumer op and then RE-READS every home into the
result — a consumer that wrote a home in place returns a wrong number, not a
lucky one. Families: i32/i64 binary, compare, unary; conversions; loads and
stores (home as address and as value); select (home as arm and as
condition); function-level `br_if` with a home value; `br_table` on a home
index; `if (param)` whose param is a home (RQ-64-MVLOWER); block fall-
through; a param-bounded loop (#663); set/tee of ANOTHER local; the #989 WAR;
`memory.fill`/`memory.copy` on home operands (#677). The modules are
generated by `scripts/gen_home_alias_class_1189.py` and committed.

EVERY expected value comes from wasmtime, live; linear memory is pre-filled
with the same byte pattern on both sides so loads are meaningful and stores
are observed. Signatures are read from the module's export types — nothing
is typed twice.

DECLINES ARE PINNED EXACTLY. A leg that refuses a function (RV32's #312 i64
params; AArch64 shapes it does not lower yet) leaves no symbol; the set of
missing symbols per (module, leg) must EQUAL the table below — an
unexpected decline is red (reach regressed), and a pinned decline that now
compiles is red too (reach moved; update the pin in the PR that moved it).

TWO HALVES, ONE CASE TABLE (the #1190 discipline). The oracle's first run
on main (`af819788`) found THREE silent wrong answers, each a different
consumer: #1221 (aarch64 `rotl` negates the count operand IN PLACE — a param
homed there reads back as `-count`), #1222 (the direct selector's
`local.set`/`local.tee` of a register-homed i64 param writes only the LO
half), #1223 (the optimized path folds `(x - x) + x` to the constant 0 — an
IR fold/DCE defect, not an alias, filed and pinned OPEN).
  RED half  — `home_alias_class_1189_red_main.json` holds the objects main
              emitted for the five (module, leg) pairs carrying those
              vectors. Every run re-executes them; the pinned vectors must
              return EXACTLY the recorded wrong value AND differ from live
              wasmtime, the rest must match. The permanent proof this
              harness can see the defects — a differential that has never
              been red is a green board of unknown potency.
  LIVE half — the current compiler on all four legs must match wasmtime,
              except the KNOWN_OPEN vectors (#1223), which must still return
              the recorded wrong value until their fix flips the pin.

CAPTURE (how the fixture was made, and how to remake it): check out main at
af819788 in a scratch tree, `cargo build --features riscv --bin synth`, then
  python3 scripts/repro/home_alias_class_1189_differential.py \
      --capture <that tree>/target/debug/synth --rev af819788

Run (needs wasmtime + unicorn + pyelftools):
  SYNTH=./target/debug/synth python3 scripts/repro/home_alias_class_1189_differential.py
  … --print-skips   prints the measured decline table (to re-derive the pin)
"""

import base64
import io
import json
import os
import struct
import subprocess
import sys
import tempfile
from pathlib import Path

import wasmtime
from elftools.elf.elffile import ELFFile
from unicorn import (
    UC_ARCH_ARM,
    UC_ARCH_ARM64,
    UC_ARCH_RISCV,
    UC_MODE_ARM,
    UC_MODE_RISCV32,
    UC_MODE_THUMB,
    Uc,
    UcError,
)
from unicorn import arm64_const as a64
from unicorn import arm_const as ac
from unicorn import riscv_const as rc

HERE = Path(__file__).parent
SYNTH = os.environ.get("SYNTH", "./target/debug/synth")

MODULES = {
    "i32": HERE / "home_alias_class_1189_i32.wat",
    "i64": HERE / "home_alias_class_1189_i64.wat",
    "promo": HERE / "home_alias_class_1189_promo.wat",
}
LEG_FLAGS = {
    "arm-reloc": ["--target", "cortex-m4", "--relocatable"],
    "arm-self": ["--target", "cortex-m4"],
    "rv32-reloc": ["-b", "riscv", "--target", "riscv32imac", "--relocatable"],
    "aarch64": ["-b", "aarch64"],
}
LEGS = list(LEG_FLAGS)
M32, M64 = 0xFFFFFFFF, 0xFFFFFFFFFFFFFFFF

# (module, leg) -> the exports that leg REFUSES (no symbol in the object).
# Measured; every entry is a loud per-function decline under
# --allow-skipped-exports. Re-derive with --print-skips.
EXPECTED_SKIPS = {
    ("i32", "aarch64"): {"brif_fn", "copy", "fill", "ifparam"},
    ("i32", "arm-self"): {"ifparam"},
    ("i32", "rv32-reloc"): {"b_rotl", "b_rotr", "brif_fn", "copy", "fill", "ifparam",
                            "u_clz", "u_ctz", "u_popcnt"},
    ("i64", "arm-reloc"): {"c_eq", "c_ge_s", "c_ge_u", "c_gt_s", "c_gt_u", "c_le_s",
                           "c_le_u", "c_lt_s", "c_lt_u", "c_ne"},
    ("i64", "arm-self"): {"c_eq", "c_ge_s", "c_ge_u", "c_gt_s", "c_gt_u", "c_le_s",
                          "c_le_u", "c_lt_s", "c_lt_u", "c_ne"},
    # #312: an i64 param declines on RV32 — only the two i32-param functions run.
    ("i64", "rv32-reloc"): {"b_add", "b_and", "b_div_s", "b_div_u", "b_mul", "b_or",
                            "b_rem_s", "b_rem_u", "b_rotl", "b_rotr", "b_shl", "b_shr_s",
                            "b_shr_u", "b_sub", "b_xor", "c_eq", "c_ge_s", "c_ge_u",
                            "c_gt_s", "c_gt_u", "c_le_s", "c_le_u", "c_lt_s", "c_lt_u",
                            "c_ne", "ld_i64_load", "ld_i64_load16_s", "ld_i64_load16_u",
                            "ld_i64_load32_s", "ld_i64_load32_u", "ld_i64_load8_s",
                            "ld_i64_load8_u", "sel64", "st_i64_store", "st_i64_store16",
                            "st_i64_store32", "st_i64_store8", "u_clz", "u_ctz", "u_eqz",
                            "u_extend16_s", "u_extend32_s", "u_extend8_s", "u_popcnt",
                            "war64", "wrap"},
    ("promo", "aarch64"): {"p_brif", "p_fill"},
    ("promo", "rv32-reloc"): {"p_brif", "p_fill"},
}

# ── the RED half: main's own objects (see CAPTURE in the docstring) ─────────
FIXTURE = HERE / "home_alias_class_1189_red_main.json"
FIXTURE_LEGS = [("i32", "arm-self"), ("i32", "aarch64"),
                ("i64", "arm-reloc"), ("i64", "arm-self"), ("i64", "aarch64")]
# (module, leg, fn, args) -> the value main's bytes return. A pinned vector
# must (a) equal the recorded value and (b) differ from live wasmtime — "do
# not manufacture a wrong answer you did not observe". Everything else in the
# fixture is pinned MATCH.
PINNED_WRONG = {
    # #1221: aarch64 rotl negates the count in place — the param reads -b.
    ("i32", "aarch64", "b_rotl", (7, 3)): 0x3C,
    ("i32", "aarch64", "b_rotl", (0x80000005, 3)): 0x8000002E,
    ("i32", "aarch64", "b_rotl", ((-9) & M32, 4)): 0xFFFFFF72,
    ("i64", "aarch64", "b_rotl", (0x100000007, 0x300000003)): 0x60000003C,
    ("i64", "aarch64", "b_rotl", (7, 3)): 0x3C,
    ("i64", "aarch64", "b_rotl", ((-9) & M64, 4)): 0xFFFFFFFFFFFFFF72,
    ("i64", "aarch64", "b_rotl", (0x100000007, 35)): 0x38FFFFFFEC,
    # #1222: the direct selector's i64-param local.set writes only the lo half.
    ("i64", "arm-reloc", "war64", (0x100000007, 0x300000003)): 0x50000000E,
    ("i64", "arm-self", "war64", (0x100000007, 0x300000003)): 0x50000000E,
    # #1223: the optimized path folds (x - x) + x to 0.
    ("i32", "arm-self", "same_twice", (7,)): 0x0,
}
# Vectors STILL wrong on the live compiler because their defect is filed and
# OPEN: the live half requires the recorded wrong value (and a divergence from
# wasmtime), so the fix that closes the issue must flip this pin in its PR.
KNOWN_OPEN = {
    ("i32", "arm-self", "same_twice", (7,)): (0x0, "#1223"),
}

CODE, LIN = 0x100000, 0x40000
LINMEM_SELF = 0x20000100  # the optimized path's absolute linear-memory base
LIN_A64 = 0x1000000
MEM_BYTES = 0x10000  # one wasm page, the modules' declared memory
STACK_BASE, STACK_SIZE = 0x80000, 0x10000
SP0 = STACK_BASE + 0xC000
RET_PAD = CODE + 0x38000
RET_FLAT = 0x200000
MEM_POISON = 0xDEADBEEF

# The byte pattern both sides see in linear memory before every call.
PREFILL = bytes(((i * 7 + 3) & 0xFF) for i in range(MEM_BYTES))


def canary(i):
    """A value that NAMES the register it seeds."""
    return (0xC0DE0000 | i) & M32


def die(msg):
    print(f"FATAL: {msg}")
    sys.exit(1)


# ── vectors per function (by family prefix; explicit where the shape needs it)
def vectors(module, fn):
    if module == "i32":
        table = {
            "same_twice": [(7,)],
            "sel_then": [(7, 0), (7, 1)],
            "sel_else": [(7, 0), (7, 1)],
            "sel_cond": [(0, 3), (4, 3)],
            "brif_fn": [(0, 5), (2, 5)],
            "brif_blk": [(0, 5), (2, 5)],
            "brtab": [(0, 1), (1, 1), (2, 1), (5, 1)],
            "ifparam": [(7, 0), (7, 1)],
            "blkfall": [(7, 3)],
            "loopcnt": [(3, 10), (0, 10)],
            "set_other": [(7, 3)],
            "tee_other": [(7, 3)],
            "war_set": [(7, 3)],
            "fill": [(8, 0xAB, 4), (8, 0, 0)],
            "copy": [(16, 0, 8), (16, 4, 0)],
        }
        if fn in table:
            return table[fn]
        if fn.startswith("hi_"):
            return [(0, 0, 7, 3), (1, 2, 0x80000005, 3)]
        if fn.startswith("b_"):
            return [(7, 3), (0x80000005, 3), ((-9) & M32, 4)]
        if fn.startswith("c_"):
            return [(7, 3), (3, 7), (5, 5)]
        if fn.startswith("u_"):
            return [(0xF0,), (0,), (M32,)]
        if fn.startswith("ld_"):
            return [(0, 3), (4, 3), (8, 3), (12, 2)]
        if fn.startswith("st_"):
            return [(4, 0x1234ABCD), (8, 0x80)]
    if module == "i64":
        table = {
            "wrap": [(0x100000007, 0x300000003)],
            "ext_s": [((-5) & M32, 3), (7, 3)],
            "ext_u": [((-5) & M32, 3), (7, 3)],
            "sel64": [(0x100000007, 0), (0x100000007, 5)],
            "war64": [(0x100000007, 0x300000003)],
        }
        if fn in table:
            return table[fn]
        if fn.startswith("b_"):
            return [(0x100000007, 0x300000003), (7, 3), ((-9) & M64, 4),
                    (0x100000007, 35)]
        if fn.startswith("c_"):
            return [(0x100000007, 0x300000003), (3, 7)]
        if fn.startswith("u_"):
            return [(0xF0,), (0x100000000,)]
        if fn.startswith("ld_"):
            return [(0, 0x300000003), (8, 5)]
        if fn.startswith("st_"):
            return [(8, 0x1122334455667788), (16, 0x80)]
    if module == "promo":
        if fn == "p_brif":
            return [(5,), (0,)]
        return [(5,), (0x40,)]
    die(f"no vectors for {module}/{fn}")


# ── ELF loading ─────────────────────────────────────────────────────────────
def load_object(data, leg):
    """(symbols, .text bytes, .text base). These modules carry no calls, so
    any relocation is fatal — this harness executes what it can see."""
    e = ELFFile(io.BytesIO(data))
    symtab = [s for s in e.iter_sections() if s["sh_type"] == "SHT_SYMTAB"][0]
    syms = {s.name: s["st_value"] for s in symtab.iter_symbols() if s.name}
    sec = e.get_section_by_name(".text")
    base = sec["sh_addr"]
    text = bytes(sec.data())
    for rel in e.iter_sections():
        if rel["sh_type"] in ("SHT_REL", "SHT_RELA"):
            for r in rel.iter_relocations():
                name = symtab.get_symbol(r["r_info_sym"]).name
                die(f"unexpected relocation type {r['r_info_type']} -> "
                    f"{name!r} on leg {leg}")
    return syms, text, base


# ── emulators ───────────────────────────────────────────────────────────────
def _pack_args32(write, regs, widths, args):
    """AAPCS/ilp32: a 64-bit value takes an even-aligned pair, lo first."""
    ri = 0
    for w, a in zip(widths, args):
        if w == 32:
            write(regs[ri], a & M32)
            ri += 1
        else:
            if ri % 2:
                ri += 1
            write(regs[ri], a & M32)
            write(regs[ri + 1], (a >> 32) & M32)
            ri += 2


def run_arm(obj, name, sig, args, self_contained):
    syms, text, base = obj
    if name not in syms:
        return None, f"symbol {name} missing from .symtab"
    widths, ret = sig
    addr = (syms[name] - base) & ~1
    mu = Uc(UC_ARCH_ARM, UC_MODE_THUMB)
    mu.mem_map(CODE, 0x40000)
    mu.mem_map(LIN, 0x20000)
    mu.mem_map(LINMEM_SELF & ~0xFFFF, 0x20000)
    mu.mem_map(STACK_BASE, STACK_SIZE)
    mu.mem_write(CODE, text)
    mu.mem_write(LIN, PREFILL)
    mu.mem_write(LINMEM_SELF, PREFILL)
    mu.mem_write(STACK_BASE,
                 struct.pack("<I", MEM_POISON) * ((SP0 - STACK_BASE) // 4))
    for i in (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12):
        mu.reg_write(getattr(ac, f"UC_ARM_REG_R{i}"), canary(i))
    mu.reg_write(ac.UC_ARM_REG_SP, SP0)
    mu.reg_write(ac.UC_ARM_REG_R11, LINMEM_SELF if self_contained else LIN)
    regs = [ac.UC_ARM_REG_R0, ac.UC_ARM_REG_R1, ac.UC_ARM_REG_R2,
            ac.UC_ARM_REG_R3]
    _pack_args32(mu.reg_write, regs, widths, args)
    mu.reg_write(ac.UC_ARM_REG_LR, RET_PAD | 1)
    try:
        mu.emu_start((CODE + addr) | 1, RET_PAD, count=400_000)
    except UcError as ex:
        return None, str(ex)
    r0 = mu.reg_read(ac.UC_ARM_REG_R0) & M32
    if ret == 64:
        return r0 | (mu.reg_read(ac.UC_ARM_REG_R1) & M32) << 32, ""
    return r0, ""


RV_SEED = [
    (rc.UC_RISCV_REG_T0, 16), (rc.UC_RISCV_REG_T1, 17), (rc.UC_RISCV_REG_T2, 18),
    (rc.UC_RISCV_REG_T3, 19), (rc.UC_RISCV_REG_T4, 20), (rc.UC_RISCV_REG_T5, 21),
    (rc.UC_RISCV_REG_T6, 22),
    (rc.UC_RISCV_REG_S1, 23), (rc.UC_RISCV_REG_S2, 24), (rc.UC_RISCV_REG_S3, 25),
    (rc.UC_RISCV_REG_S4, 26), (rc.UC_RISCV_REG_S5, 27), (rc.UC_RISCV_REG_S6, 28),
    (rc.UC_RISCV_REG_S8, 40), (rc.UC_RISCV_REG_S9, 41), (rc.UC_RISCV_REG_S10, 42),
    (rc.UC_RISCV_REG_A1, 29), (rc.UC_RISCV_REG_A2, 30), (rc.UC_RISCV_REG_A3, 31),
]


def run_rv32(obj, name, sig, args):
    syms, text, base = obj
    if name not in syms:
        return None, f"symbol {name} missing from .symtab"
    widths, ret = sig
    addr = syms[name] - base
    mu = Uc(UC_ARCH_RISCV, UC_MODE_RISCV32)
    mu.mem_map(CODE, 0x40000)
    mu.mem_map(LIN, 0x20000)
    mu.mem_map(STACK_BASE, STACK_SIZE)
    mu.mem_map(RET_FLAT, 0x1000)
    mu.mem_write(CODE, text)
    mu.mem_write(LIN, PREFILL)
    mu.mem_write(STACK_BASE,
                 struct.pack("<I", MEM_POISON) * ((SP0 - STACK_BASE) // 4))
    for reg, i in RV_SEED:
        mu.reg_write(reg, canary(i))
    mu.reg_write(rc.UC_RISCV_REG_SP, SP0)
    mu.reg_write(rc.UC_RISCV_REG_S11, LIN)
    regs = [rc.UC_RISCV_REG_A0, rc.UC_RISCV_REG_A1, rc.UC_RISCV_REG_A2,
            rc.UC_RISCV_REG_A3]
    _pack_args32(mu.reg_write, regs, widths, args)
    mu.reg_write(rc.UC_RISCV_REG_RA, RET_FLAT)
    try:
        mu.emu_start(CODE + addr, RET_FLAT, count=400_000)
    except UcError as ex:
        return None, str(ex)
    a0 = mu.reg_read(rc.UC_RISCV_REG_A0) & M32
    if ret == 64:
        return a0 | (mu.reg_read(rc.UC_RISCV_REG_A1) & M32) << 32, ""
    return a0, ""


def run_a64(obj, name, sig, args):
    syms, text, base = obj
    if name not in syms:
        return None, f"symbol {name} missing from .symtab"
    widths, ret = sig
    addr = (syms[name] - base) & ~1
    mu = Uc(UC_ARCH_ARM64, UC_MODE_ARM)
    mu.mem_map(CODE, 0x40000)
    mu.mem_map(STACK_BASE, STACK_SIZE)
    mu.mem_map(RET_FLAT, 0x1000)
    mu.mem_map(LIN_A64, 0x20000)
    mu.mem_write(CODE, text)
    mu.mem_write(LIN_A64, PREFILL)
    mu.reg_write(a64.UC_ARM64_REG_SP, SP0)
    mu.reg_write(a64.UC_ARM64_REG_LR, RET_FLAT)
    for i in range(0, 16):
        mu.reg_write(getattr(a64, f"UC_ARM64_REG_X{i}"), canary(i))
    mu.reg_write(a64.UC_ARM64_REG_X28, LIN_A64)
    regs = [a64.UC_ARM64_REG_X0, a64.UC_ARM64_REG_X1, a64.UC_ARM64_REG_X2,
            a64.UC_ARM64_REG_X3]
    for r, (w, a) in zip(regs, zip(widths, args)):
        mu.reg_write(r, a & (M32 if w == 32 else M64))
    try:
        mu.emu_start(CODE + addr, RET_FLAT, count=400_000)
    except UcError as ex:
        return None, str(ex)
    if ret == 32:
        return mu.reg_read(a64.UC_ARM64_REG_W0) & M32, ""
    return mu.reg_read(a64.UC_ARM64_REG_X0) & M64, ""


def run_leg(leg, obj, name, sig, args):
    if leg.startswith("arm"):
        return run_arm(obj, name, sig, args, leg == "arm-self")
    if leg.startswith("rv32"):
        return run_rv32(obj, name, sig, args)
    return run_a64(obj, name, sig, args)


# ── the reference ───────────────────────────────────────────────────────────
class Reference:
    """wasmtime, one fresh instance per call (bulk ops mutate memory), memory
    pre-filled with PREFILL exactly like the emulators."""

    def __init__(self):
        self.engine = wasmtime.Engine()
        self.modules = {}

    def module(self, name):
        if name not in self.modules:
            self.modules[name] = wasmtime.Module.from_file(self.engine,
                                                            str(MODULES[name]))
        return self.modules[name]

    def signatures(self, name):
        """fn -> ([param widths], ret width) from the export types."""
        out = {}
        for exp in self.module(name).exports:
            if isinstance(exp.type, wasmtime.FuncType):
                widths = [64 if str(p) == "i64" else 32 for p in exp.type.params]
                rets = exp.type.results
                if len(rets) != 1:
                    die(f"{name}/{exp.name}: expected exactly one result")
                out[exp.name] = (widths, 64 if str(rets[0]) == "i64" else 32)
        return out

    def call(self, name, fn, sig, args):
        widths, ret = sig
        store = wasmtime.Store(self.engine)
        inst = wasmtime.Instance(store, self.module(name), [])
        exports = inst.exports(store)
        if "memory" in exports:
            exports["memory"].write(store, PREFILL, 0)
        f = exports[fn]
        call = []
        for w, a in zip(widths, args):
            if w == 32:
                call.append(struct.unpack("<i", struct.pack("<I", a & M32))[0])
            else:
                call.append(struct.unpack("<q", struct.pack("<Q", a & M64))[0])
        return f(store, *call) & (M32 if ret == 32 else M64)


def compile_module(module, leg, out):
    return subprocess.run(
        [SYNTH, "compile", str(MODULES[module]), *LEG_FLAGS[leg],
         "--all-exports", "--allow-skipped-exports", "-o", out],
        capture_output=True, text=True, env={"PATH": "/usr/bin:/bin"},
    )


def fmt(v):
    return f"{v:#x}" if v is not None else "<none>"


def capture(old_synth, rev):
    fix = {
        "provenance": {
            "issue": "#1189 / RQ-65-ALIASCLASS",
            "source_rev": rev,
            "note": "objects emitted by main's compiler for the legs carrying "
                    "the #1221/#1222/#1223 wrong vectors; recipe in this "
                    "oracle's docstring",
        },
        "legs": {},
    }
    saved = globals()["SYNTH"]
    globals()["SYNTH"] = old_synth
    try:
        for module, leg in FIXTURE_LEGS:
            with tempfile.TemporaryDirectory() as td:
                out = os.path.join(td, "m.o")
                r = compile_module(module, leg, out)
                if not os.path.exists(out):
                    die(f"capture: {module}/{leg} produced no object:\n{r.stderr[-600:]}")
                blob = Path(out).read_bytes()
            fix["legs"][f"{module}_{leg}"] = {"object_b64": base64.b64encode(blob).decode()}
            print(f"captured {module}/{leg}: {len(blob)} bytes")
    finally:
        globals()["SYNTH"] = saved
    FIXTURE.write_text(json.dumps(fix, indent=2) + "\n")
    print(f"wrote {FIXTURE}")
    return 0


def main():
    argv = sys.argv[1:]
    if len(argv) == 4 and argv[0] == "--capture" and argv[2] == "--rev":
        return capture(argv[1], argv[3])
    print_skips = argv == ["--print-skips"]
    if argv and not print_skips:
        die(f"usage: {sys.argv[0]} [--print-skips | --capture <main synth> --rev <sha>]")

    ref = Reference()
    fails = 0
    emulations = 0

    # ── RED half: main's own bytes vs wasmtime ──────────────────────────────
    fix = json.loads(FIXTURE.read_text())
    print(f"== red half: fixture rev {fix['provenance']['source_rev'][:12]} (main) ==")
    wrong_seen = fix_match = 0
    pinned_hit = set()
    for module, leg in FIXTURE_LEGS:
        entry = fix["legs"].get(f"{module}_{leg}")
        if entry is None:
            die(f"fixture leg {module}/{leg} missing; re-capture")
        obj = load_object(base64.b64decode(entry["object_b64"]), leg)
        sigs = ref.signatures(module)
        for fn, sig in sigs.items():
            if fn not in obj[0]:
                continue  # main declined it; the live half pins declines
            for args in vectors(module, fn):
                want = ref.call(module, fn, sig, args)
                got, err = run_leg(leg, obj, fn, sig, args)
                emulations += 1
                if err:
                    print(f"  FAIL fixture {module}/{leg} {fn}{tuple(args)}: emulator error: {err}")
                    fails += 1
                    continue
                key = (module, leg, fn, tuple(args))
                pinned = PINNED_WRONG.get(key)
                if pinned is not None:
                    ok = got == pinned and got != want
                    wrong_seen += ok
                    pinned_hit.add(key)
                    label = ("SILENT-WRONG as pinned" if ok
                             else f"NOT the pinned miscompile (pinned {pinned:#x})")
                    print(f"  {'ok  ' if ok else 'FAIL'} fixture {module}/{leg} "
                          f"{fn}{tuple(args)} -> {fmt(got)} (wasmtime {want:#x}) — {label}")
                else:
                    ok = got == want
                    fix_match += ok
                    if not ok:
                        print(f"  FAIL fixture {module}/{leg} {fn}{tuple(args)} -> "
                              f"{fmt(got)} (wasmtime {want:#x}) — diverged, not pinned")
                fails += not ok
    missing = set(PINNED_WRONG) - pinned_hit
    if missing:
        print(f"  FAIL pinned wrong vectors never executed: {sorted(missing)}")
        fails += 1

    # ── LIVE half: the current compiler on all four legs ────────────────────
    print("== live half: current compiler vs wasmtime, four legs ==")
    live_ok = live_bad = open_seen = 0
    measured_skips = {}
    for module in MODULES:
        sigs = ref.signatures(module)
        for leg in LEGS:
            with tempfile.TemporaryDirectory() as td:
                out = os.path.join(td, "m.o")
                r = compile_module(module, leg, out)
                log = r.stderr + r.stdout
                if "panicked at" in log or r.returncode == 101:
                    print(f"  FAIL {module}/{leg}: PANIC:\n{log[-600:]}")
                    fails += 1
                    continue
                if not os.path.exists(out):
                    print(f"  FAIL {module}/{leg}: no object (rc={r.returncode}):"
                          f"\n{log[-600:]}")
                    fails += 1
                    continue
                obj = load_object(Path(out).read_bytes(), leg)
            syms = obj[0]
            missing = {fn for fn in sigs if fn not in syms}
            measured_skips[(module, leg)] = missing
            expected = EXPECTED_SKIPS.get((module, leg), set())
            if missing != expected and not print_skips:
                new = sorted(missing - expected)
                gone = sorted(expected - missing)
                print(f"  FAIL {module}/{leg}: decline table drifted — "
                      f"newly declined {new}, now compiling {gone}")
                fails += 1
            for fn, sig in sigs.items():
                if fn in missing:
                    continue
                for args in vectors(module, fn):
                    want = ref.call(module, fn, sig, args)
                    got, err = run_leg(leg, obj, fn, sig, args)
                    emulations += 1
                    if err:
                        print(f"  FAIL {module}/{leg} {fn}{tuple(args)}: "
                              f"emulator error: {err}")
                        live_bad += 1
                        continue
                    known = KNOWN_OPEN.get((module, leg, fn, tuple(args)))
                    if known is not None:
                        rec, issue = known
                        ok = got == rec and got != want
                        open_seen += ok
                        note = (f"still the recorded wrong answer, {issue} open" if ok
                                else f"pin drifted: fix landed or value moved ({issue})")
                        print(f"  {'ok  ' if ok else 'FAIL'} {module}/{leg} {fn}{tuple(args)} -> "
                              f"{fmt(got)} (wasmtime {want:#x}) — {note}")
                        live_ok += ok
                        live_bad += not ok
                        continue
                    ok = got == want
                    live_ok += ok
                    live_bad += not ok
                    if not ok:
                        print(f"  FAIL {module}/{leg} {fn}{tuple(args)} -> "
                              f"{fmt(got)} (wasmtime: {want:#x}) — SILENT WRONG ANSWER")
            print(f"  {module}/{leg}: {len(sigs) - len(missing)} functions executed, "
                  f"{len(missing)} declined")
    fails += live_bad

    if print_skips:
        print("EXPECTED_SKIPS = {")
        for (m, leg), sk in sorted(measured_skips.items()):
            if sk:
                print(f'    ("{m}", "{leg}"): {sorted(sk)!r},')
        print("}")
        return 0

    print(f"\nsilent-wrong vectors: {wrong_seen} (of {len(PINNED_WRONG)} pinned); "
          f"fixture match vectors: {fix_match}")
    print(f"known-open vectors: {open_seen} (of {len(KNOWN_OPEN)})")
    print(f"live vectors: {live_ok} matched, {live_bad} diverged")
    print(f"emulations: {emulations}")
    if wrong_seen != len(PINNED_WRONG):
        print(f"VACUOUS: silent-wrong vectors={wrong_seen}, want {len(PINNED_WRONG)} — "
              f"the red half no longer demonstrates the miscompiles it exists to remember")
        return 1
    if fix_match == 0 or live_ok == 0:
        print("VACUOUS: no match vector executed")
        return 1
    if fails:
        print(f"RESULT: FAIL ({fails})")
        return 1
    print("RESULT: PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
