(module
  ;; RQ-73-ISLANDPASS (#1331). Generated by scripts/repro/gen_islandpass_1331.py.
  ;;
  ;; A 4 KB+ function whose literal pool needs an inline island, with the
  ;; two things the v0.72 execution differential could not see:
  ;;   * a direct CALL inside the spanned region, so the stream carries an
  ;;     R_ARM_THM_CALL whose offset is recorded from code.len();
  ;;   * THREE distinct static-data literals, so a pool patch landing in
  ;;     the wrong pool is observable rather than degenerate.
  ;; plus a forward `br_if` that SPANS the island placement point.
  (memory 1)
  (data (i32.const 1024) "islandpass-A")
  (data (i32.const 2048) "islandpass-B")
  (data (i32.const 3072) "islandpass-C")

  ;; The callee. A real BL inside the spanned region is the point.
  (func $helper (param i32) (result i32)
    local.get 0
    i32.const 3
    i32.mul
    i32.const 7
    i32.add
  )

  (func $big (export "big") (param i32) (result i32)
    (local i32) (local i64) (local i32)
    (block
      ;; literal 1 — loaded BEFORE the span opens
      i32.const 1024
      i32.load
      local.set 1
      ;; the branch that SPANS the island placement
      local.get 0
      br_if 0
      ;; a direct call INSIDE the spanned region
      local.get 1
      call $helper
      local.set 3
      ;; literal 2, also inside the span
      i32.const 2048
      i32.load
      local.get 3
      i32.add
      local.set 3
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
      local.get 2
      i64.const 8
      i64.mul
      local.set 2
      local.get 2
      i64.const 2
      i64.mul
      local.set 2
      local.get 2
      i64.const 3
      i64.mul
      local.set 2
      local.get 2
      i64.const 4
      i64.mul
      local.set 2
      local.get 2
      i64.const 5
      i64.mul
      local.set 2
      local.get 2
      i64.const 6
      i64.mul
      local.set 2
      local.get 2
      i64.const 7
      i64.mul
      local.set 2
    )
    ;; literal 3 — after the span closes, so its pool must still resolve
    i32.const 3072
    i32.load
    local.get 1
    i32.add
    local.get 3
    i32.add
    local.get 2
    i32.wrap_i64
    i32.add
  )
)
