(module
  ;; RQ-74-ISLANDREACH (#1331). Generated by scripts/repro/gen_islandpass_1331.py.
  ;; shape: nested (br 1 out of an inner block)
  ;;
  ;; A 4 KB+ function whose literal pool needs an inline island, with a
  ;; nested (br 1 out of an inner block) branch that SPANS the island placement point, a direct CALL
  ;; inside the spanned region, and three distinct static-data literals
  ;; loaded before / inside / after the span.
  (memory 1)
  (data (i32.const 1024) "islandreach-A")
  (data (i32.const 2048) "islandreach-B")
  (data (i32.const 3072) "islandreach-C")

  (func $helper (param i32) (result i32)
    local.get 0
    i32.const 3
    i32.mul
    i32.const 7
    i32.add
  )

  (func $big (export "big") (param i32) (result i32)
    (local i32) (local i64) (local i32)
    (block
      (block
        ;; seed the i64 accumulator FROM THE PARAM (see backward()).
        local.get 0
        i64.extend_i32_u
        i64.const 1
        i64.or
        local.set 2
        ;; literal 1 — loaded BEFORE the span opens
        i32.const 1024
        i32.load
        local.set 1
        ;; the branch that SPANS the island, out of TWO blocks
        local.get 0
        br_if 1
        ;; a direct call INSIDE the spanned region
        local.get 1
        call $helper
        local.set 3
        ;; literal 2, also inside the span
        i32.const 2048
        i32.load
        local.get 3
        i32.add
        local.set 3
          local.get 2
          i64.const 3
          i64.mul
          local.set 2
          local.get 2
          i64.const 5
          i64.mul
          local.set 2
          local.get 2
          i64.const 7
          i64.mul
          local.set 2
          local.get 2
          i64.const 9
          i64.mul
          local.set 2
          local.get 2
          i64.const 11
          i64.mul
          local.set 2
          local.get 2
          i64.const 13
          i64.mul
          local.set 2
          local.get 2
          i64.const 3
          i64.mul
          local.set 2
          local.get 2
          i64.const 5
          i64.mul
          local.set 2
          local.get 2
          i64.const 7
          i64.mul
          local.set 2
          local.get 2
          i64.const 9
          i64.mul
          local.set 2
          local.get 2
          i64.const 11
          i64.mul
          local.set 2
          local.get 2
          i64.const 13
          i64.mul
          local.set 2
          local.get 2
          i64.const 3
          i64.mul
          local.set 2
          local.get 2
          i64.const 5
          i64.mul
          local.set 2
          local.get 2
          i64.const 7
          i64.mul
          local.set 2
          local.get 2
          i64.const 9
          i64.mul
          local.set 2
          local.get 2
          i64.const 11
          i64.mul
          local.set 2
          local.get 2
          i64.const 13
          i64.mul
          local.set 2
          local.get 2
          i64.const 3
          i64.mul
          local.set 2
          local.get 2
          i64.const 5
          i64.mul
          local.set 2
          local.get 2
          i64.const 7
          i64.mul
          local.set 2
          local.get 2
          i64.const 9
          i64.mul
          local.set 2
          local.get 2
          i64.const 11
          i64.mul
          local.set 2
          local.get 2
          i64.const 13
          i64.mul
          local.set 2
          local.get 2
          i64.const 3
          i64.mul
          local.set 2
          local.get 2
          i64.const 5
          i64.mul
          local.set 2
          local.get 2
          i64.const 7
          i64.mul
          local.set 2
          local.get 2
          i64.const 9
          i64.mul
          local.set 2
          local.get 2
          i64.const 11
          i64.mul
          local.set 2
          local.get 2
          i64.const 13
          i64.mul
          local.set 2
          local.get 2
          i64.const 3
          i64.mul
          local.set 2
          local.get 2
          i64.const 5
          i64.mul
          local.set 2
          local.get 2
          i64.const 7
          i64.mul
          local.set 2
          local.get 2
          i64.const 9
          i64.mul
          local.set 2
          local.get 2
          i64.const 11
          i64.mul
          local.set 2
          local.get 2
          i64.const 13
          i64.mul
          local.set 2
          local.get 2
          i64.const 3
          i64.mul
          local.set 2
          local.get 2
          i64.const 5
          i64.mul
          local.set 2
          local.get 2
          i64.const 7
          i64.mul
          local.set 2
          local.get 2
          i64.const 9
          i64.mul
          local.set 2
          local.get 2
          i64.const 11
          i64.mul
          local.set 2
          local.get 2
          i64.const 13
          i64.mul
          local.set 2
          local.get 2
          i64.const 3
          i64.mul
          local.set 2
          local.get 2
          i64.const 5
          i64.mul
          local.set 2
          local.get 2
          i64.const 7
          i64.mul
          local.set 2
          local.get 2
          i64.const 9
          i64.mul
          local.set 2
          local.get 2
          i64.const 11
          i64.mul
          local.set 2
          local.get 2
          i64.const 13
          i64.mul
          local.set 2
          local.get 2
          i64.const 3
          i64.mul
          local.set 2
          local.get 2
          i64.const 5
          i64.mul
          local.set 2
          local.get 2
          i64.const 7
          i64.mul
          local.set 2
          local.get 2
          i64.const 9
          i64.mul
          local.set 2
          local.get 2
          i64.const 11
          i64.mul
          local.set 2
          local.get 2
          i64.const 13
          i64.mul
          local.set 2
          local.get 2
          i64.const 3
          i64.mul
          local.set 2
          local.get 2
          i64.const 5
          i64.mul
          local.set 2
          local.get 2
          i64.const 7
          i64.mul
          local.set 2
          local.get 2
          i64.const 9
          i64.mul
          local.set 2
          local.get 2
          i64.const 11
          i64.mul
          local.set 2
          local.get 2
          i64.const 13
          i64.mul
          local.set 2
          local.get 2
          i64.const 3
          i64.mul
          local.set 2
          local.get 2
          i64.const 5
          i64.mul
          local.set 2
          local.get 2
          i64.const 7
          i64.mul
          local.set 2
          local.get 2
          i64.const 9
          i64.mul
          local.set 2
          local.get 2
          i64.const 11
          i64.mul
          local.set 2
          local.get 2
          i64.const 13
          i64.mul
          local.set 2
          local.get 2
          i64.const 3
          i64.mul
          local.set 2
          local.get 2
          i64.const 5
          i64.mul
          local.set 2
          local.get 2
          i64.const 7
          i64.mul
          local.set 2
          local.get 2
          i64.const 9
          i64.mul
          local.set 2
          local.get 2
          i64.const 11
          i64.mul
          local.set 2
          local.get 2
          i64.const 13
          i64.mul
          local.set 2
          local.get 2
          i64.const 3
          i64.mul
          local.set 2
          local.get 2
          i64.const 5
          i64.mul
          local.set 2
          local.get 2
          i64.const 7
          i64.mul
          local.set 2
          local.get 2
          i64.const 9
          i64.mul
          local.set 2
          local.get 2
          i64.const 11
          i64.mul
          local.set 2
          local.get 2
          i64.const 13
          i64.mul
          local.set 2
          local.get 2
          i64.const 3
          i64.mul
          local.set 2
          local.get 2
          i64.const 5
          i64.mul
          local.set 2
          local.get 2
          i64.const 7
          i64.mul
          local.set 2
          local.get 2
          i64.const 9
          i64.mul
          local.set 2
          local.get 2
          i64.const 11
          i64.mul
          local.set 2
          local.get 2
          i64.const 13
          i64.mul
          local.set 2
          local.get 2
          i64.const 3
          i64.mul
          local.set 2
          local.get 2
          i64.const 5
          i64.mul
          local.set 2
          local.get 2
          i64.const 7
          i64.mul
          local.set 2
          local.get 2
          i64.const 9
          i64.mul
          local.set 2
          local.get 2
          i64.const 11
          i64.mul
          local.set 2
          local.get 2
          i64.const 13
          i64.mul
          local.set 2
          local.get 2
          i64.const 3
          i64.mul
          local.set 2
          local.get 2
          i64.const 5
          i64.mul
          local.set 2
          local.get 2
          i64.const 7
          i64.mul
          local.set 2
          local.get 2
          i64.const 9
          i64.mul
          local.set 2
          local.get 2
          i64.const 11
          i64.mul
          local.set 2
          local.get 2
          i64.const 13
          i64.mul
          local.set 2
          local.get 2
          i64.const 3
          i64.mul
          local.set 2
          local.get 2
          i64.const 5
          i64.mul
          local.set 2
          local.get 2
          i64.const 7
          i64.mul
          local.set 2
          local.get 2
          i64.const 9
          i64.mul
          local.set 2
          local.get 2
          i64.const 11
          i64.mul
          local.set 2
          local.get 2
          i64.const 13
          i64.mul
          local.set 2
          local.get 2
          i64.const 3
          i64.mul
          local.set 2
          local.get 2
          i64.const 5
          i64.mul
          local.set 2
          local.get 2
          i64.const 7
          i64.mul
          local.set 2
          local.get 2
          i64.const 9
          i64.mul
          local.set 2
          local.get 2
          i64.const 11
          i64.mul
          local.set 2
          local.get 2
          i64.const 13
          i64.mul
          local.set 2
          local.get 2
          i64.const 3
          i64.mul
          local.set 2
          local.get 2
          i64.const 5
          i64.mul
          local.set 2
          local.get 2
          i64.const 7
          i64.mul
          local.set 2
          local.get 2
          i64.const 9
          i64.mul
          local.set 2
          local.get 2
          i64.const 11
          i64.mul
          local.set 2
          local.get 2
          i64.const 13
          i64.mul
          local.set 2
          local.get 2
          i64.const 3
          i64.mul
          local.set 2
          local.get 2
          i64.const 5
          i64.mul
          local.set 2
          local.get 2
          i64.const 7
          i64.mul
          local.set 2
          local.get 2
          i64.const 9
          i64.mul
          local.set 2
          local.get 2
          i64.const 11
          i64.mul
          local.set 2
          local.get 2
          i64.const 13
          i64.mul
          local.set 2
          local.get 2
          i64.const 3
          i64.mul
          local.set 2
          local.get 2
          i64.const 5
          i64.mul
          local.set 2
          local.get 2
          i64.const 7
          i64.mul
          local.set 2
          local.get 2
          i64.const 9
          i64.mul
          local.set 2
          local.get 2
          i64.const 11
          i64.mul
          local.set 2
          local.get 2
          i64.const 13
          i64.mul
          local.set 2
          local.get 2
          i64.const 3
          i64.mul
          local.set 2
          local.get 2
          i64.const 5
          i64.mul
          local.set 2
          local.get 2
          i64.const 7
          i64.mul
          local.set 2
          local.get 2
          i64.const 9
          i64.mul
          local.set 2
          local.get 2
          i64.const 11
          i64.mul
          local.set 2
          local.get 2
          i64.const 13
          i64.mul
          local.set 2
          local.get 2
          i64.const 3
          i64.mul
          local.set 2
          local.get 2
          i64.const 5
          i64.mul
          local.set 2
          local.get 2
          i64.const 7
          i64.mul
          local.set 2
          local.get 2
          i64.const 9
          i64.mul
          local.set 2
          local.get 2
          i64.const 11
          i64.mul
          local.set 2
          local.get 2
          i64.const 13
          i64.mul
          local.set 2
          local.get 2
          i64.const 3
          i64.mul
          local.set 2
          local.get 2
          i64.const 5
          i64.mul
          local.set 2
          local.get 2
          i64.const 7
          i64.mul
          local.set 2
          local.get 2
          i64.const 9
          i64.mul
          local.set 2
          local.get 2
          i64.const 11
          i64.mul
          local.set 2
          local.get 2
          i64.const 13
          i64.mul
          local.set 2
          local.get 2
          i64.const 3
          i64.mul
          local.set 2
          local.get 2
          i64.const 5
          i64.mul
          local.set 2
          local.get 2
          i64.const 7
          i64.mul
          local.set 2
          local.get 2
          i64.const 9
          i64.mul
          local.set 2
          local.get 2
          i64.const 11
          i64.mul
          local.set 2
          local.get 2
          i64.const 13
          i64.mul
          local.set 2
          local.get 2
          i64.const 3
          i64.mul
          local.set 2
          local.get 2
          i64.const 5
          i64.mul
          local.set 2
          local.get 2
          i64.const 7
          i64.mul
          local.set 2
          local.get 2
          i64.const 9
          i64.mul
          local.set 2
          local.get 2
          i64.const 11
          i64.mul
          local.set 2
          local.get 2
          i64.const 13
          i64.mul
          local.set 2
          local.get 2
          i64.const 3
          i64.mul
          local.set 2
          local.get 2
          i64.const 5
          i64.mul
          local.set 2
          local.get 2
          i64.const 7
          i64.mul
          local.set 2
          local.get 2
          i64.const 9
          i64.mul
          local.set 2
          local.get 2
          i64.const 11
          i64.mul
          local.set 2
          local.get 2
          i64.const 13
          i64.mul
          local.set 2
          local.get 2
          i64.const 3
          i64.mul
          local.set 2
          local.get 2
          i64.const 5
          i64.mul
          local.set 2
          local.get 2
          i64.const 7
          i64.mul
          local.set 2
          local.get 2
          i64.const 9
          i64.mul
          local.set 2
          local.get 2
          i64.const 11
          i64.mul
          local.set 2
          local.get 2
          i64.const 13
          i64.mul
          local.set 2
          local.get 2
          i64.const 3
          i64.mul
          local.set 2
          local.get 2
          i64.const 5
          i64.mul
          local.set 2
      )
    )
    ;; literal 3 — after the span closes, so its pool must still resolve
    i32.const 3072
    i32.load
    local.get 1
    i32.add
    local.get 3
    i32.add
    local.get 2
    i32.wrap_i64
    i32.add
  )
)
