;; #1069 (RQ-60-VFPPRESSURE increment 2) — VFP pressure from HOMED LOCALS,
;; not operand-stack depth. jess's falcon measurement (fixture credit: jess):
;;
;;     LOCALS (homed)             OPERAND STACK (#881-rescued)
;;       13 locals : ok             30 deep : ok
;;       14 locals : EXHAUSTED      60 deep : ok
;;
;; Sixty simultaneously-live f32 on the operand stack compile (the #881 spill
;; rung rescues them); fourteen in homed locals do not — a home S-register is
;; pinned for the function's extent and the #881 victim search explicitly
;; skips homes. So the 13->14 wall is HOME residence, not register-file
;; capacity, and extending the pool into callee-saved S16..S31 would only
;; move the same wall outward.
;;
;;  * live13  — jess's NEGATIVE CONTROL: must keep compiling (base path,
;;              byte-identical by construction — the rung never fires).
;;  * live14  — the red line: param home S0 + 14 pinned local homes + tree
;;              temps > 16 S-registers. Fails on cortex-m7dp before the fix.
;;  * live16  — same wall, further in (jess measured 16 exhausted too).
;;  * live24  — 24 homed locals: forces MORE frame-resident locals than the
;;              default 8-slot spill pool holds, so the fix's slot demand
;;              composes with the #587 pool-grow retry INSIDE the VFP rung
;;              (this is the test that the reworded slot-exhaustion message
;;              still triggers the grow — the substring IS control flow).
;;  * live8d  — the f64 twin on m7dp: param home D0 + 8 pinned D homes
;;              exhausts the caller-saved D0..D7 pair file.
;;
;; Every local is derived from the param (nothing constant-folds) and all are
;; consumed in ONE product tree, mirroring the falcon control-math shape
;; (attitude@0.7.0#tick / ekf@0.7.0#estimate, both phase-1 S exhaustion).
;;
;; GENERATED by scripts/repro/gen_vfp_local_1069.py — edit there, regenerate.

(module
  (func $live13 (export "live13") (param $a f32) (result f32)
    (local f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32)
    (local.set 1 (f32.mul (local.get 0) (f32.const 1.5)))
    (local.set 2 (f32.mul (local.get 0) (f32.const 2.5)))
    (local.set 3 (f32.mul (local.get 0) (f32.const 3.5)))
    (local.set 4 (f32.mul (local.get 0) (f32.const 4.5)))
    (local.set 5 (f32.mul (local.get 0) (f32.const 5.5)))
    (local.set 6 (f32.mul (local.get 0) (f32.const 6.5)))
    (local.set 7 (f32.mul (local.get 0) (f32.const 7.5)))
    (local.set 8 (f32.mul (local.get 0) (f32.const 8.5)))
    (local.set 9 (f32.mul (local.get 0) (f32.const 9.5)))
    (local.set 10 (f32.mul (local.get 0) (f32.const 10.5)))
    (local.set 11 (f32.mul (local.get 0) (f32.const 11.5)))
    (local.set 12 (f32.mul (local.get 0) (f32.const 12.5)))
    (local.set 13 (f32.mul (local.get 0) (f32.const 13.5)))
    (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (local.get 1) (local.get 2)) (local.get 3)) (local.get 4)) (local.get 5)) (local.get 6)) (local.get 7)) (local.get 8)) (local.get 9)) (local.get 10)) (local.get 11)) (local.get 12)) (local.get 13)))
  (func $live14 (export "live14") (param $a f32) (result f32)
    (local f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32)
    (local.set 1 (f32.mul (local.get 0) (f32.const 1.5)))
    (local.set 2 (f32.mul (local.get 0) (f32.const 2.5)))
    (local.set 3 (f32.mul (local.get 0) (f32.const 3.5)))
    (local.set 4 (f32.mul (local.get 0) (f32.const 4.5)))
    (local.set 5 (f32.mul (local.get 0) (f32.const 5.5)))
    (local.set 6 (f32.mul (local.get 0) (f32.const 6.5)))
    (local.set 7 (f32.mul (local.get 0) (f32.const 7.5)))
    (local.set 8 (f32.mul (local.get 0) (f32.const 8.5)))
    (local.set 9 (f32.mul (local.get 0) (f32.const 9.5)))
    (local.set 10 (f32.mul (local.get 0) (f32.const 10.5)))
    (local.set 11 (f32.mul (local.get 0) (f32.const 11.5)))
    (local.set 12 (f32.mul (local.get 0) (f32.const 12.5)))
    (local.set 13 (f32.mul (local.get 0) (f32.const 13.5)))
    (local.set 14 (f32.mul (local.get 0) (f32.const 14.5)))
    (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (local.get 1) (local.get 2)) (local.get 3)) (local.get 4)) (local.get 5)) (local.get 6)) (local.get 7)) (local.get 8)) (local.get 9)) (local.get 10)) (local.get 11)) (local.get 12)) (local.get 13)) (local.get 14)))
  (func $live16 (export "live16") (param $a f32) (result f32)
    (local f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32)
    (local.set 1 (f32.mul (local.get 0) (f32.const 1.5)))
    (local.set 2 (f32.mul (local.get 0) (f32.const 2.5)))
    (local.set 3 (f32.mul (local.get 0) (f32.const 3.5)))
    (local.set 4 (f32.mul (local.get 0) (f32.const 4.5)))
    (local.set 5 (f32.mul (local.get 0) (f32.const 5.5)))
    (local.set 6 (f32.mul (local.get 0) (f32.const 6.5)))
    (local.set 7 (f32.mul (local.get 0) (f32.const 7.5)))
    (local.set 8 (f32.mul (local.get 0) (f32.const 8.5)))
    (local.set 9 (f32.mul (local.get 0) (f32.const 9.5)))
    (local.set 10 (f32.mul (local.get 0) (f32.const 10.5)))
    (local.set 11 (f32.mul (local.get 0) (f32.const 11.5)))
    (local.set 12 (f32.mul (local.get 0) (f32.const 12.5)))
    (local.set 13 (f32.mul (local.get 0) (f32.const 13.5)))
    (local.set 14 (f32.mul (local.get 0) (f32.const 14.5)))
    (local.set 15 (f32.mul (local.get 0) (f32.const 15.5)))
    (local.set 16 (f32.mul (local.get 0) (f32.const 16.5)))
    (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (local.get 1) (local.get 2)) (local.get 3)) (local.get 4)) (local.get 5)) (local.get 6)) (local.get 7)) (local.get 8)) (local.get 9)) (local.get 10)) (local.get 11)) (local.get 12)) (local.get 13)) (local.get 14)) (local.get 15)) (local.get 16)))
  (func $live24 (export "live24") (param $a f32) (result f32)
    (local f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32 f32)
    (local.set 1 (f32.mul (local.get 0) (f32.const 1.5)))
    (local.set 2 (f32.mul (local.get 0) (f32.const 2.5)))
    (local.set 3 (f32.mul (local.get 0) (f32.const 3.5)))
    (local.set 4 (f32.mul (local.get 0) (f32.const 4.5)))
    (local.set 5 (f32.mul (local.get 0) (f32.const 5.5)))
    (local.set 6 (f32.mul (local.get 0) (f32.const 6.5)))
    (local.set 7 (f32.mul (local.get 0) (f32.const 7.5)))
    (local.set 8 (f32.mul (local.get 0) (f32.const 8.5)))
    (local.set 9 (f32.mul (local.get 0) (f32.const 9.5)))
    (local.set 10 (f32.mul (local.get 0) (f32.const 10.5)))
    (local.set 11 (f32.mul (local.get 0) (f32.const 11.5)))
    (local.set 12 (f32.mul (local.get 0) (f32.const 12.5)))
    (local.set 13 (f32.mul (local.get 0) (f32.const 13.5)))
    (local.set 14 (f32.mul (local.get 0) (f32.const 14.5)))
    (local.set 15 (f32.mul (local.get 0) (f32.const 15.5)))
    (local.set 16 (f32.mul (local.get 0) (f32.const 16.5)))
    (local.set 17 (f32.mul (local.get 0) (f32.const 17.5)))
    (local.set 18 (f32.mul (local.get 0) (f32.const 18.5)))
    (local.set 19 (f32.mul (local.get 0) (f32.const 19.5)))
    (local.set 20 (f32.mul (local.get 0) (f32.const 20.5)))
    (local.set 21 (f32.mul (local.get 0) (f32.const 21.5)))
    (local.set 22 (f32.mul (local.get 0) (f32.const 22.5)))
    (local.set 23 (f32.mul (local.get 0) (f32.const 23.5)))
    (local.set 24 (f32.mul (local.get 0) (f32.const 24.5)))
    (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (f32.mul (local.get 1) (local.get 2)) (local.get 3)) (local.get 4)) (local.get 5)) (local.get 6)) (local.get 7)) (local.get 8)) (local.get 9)) (local.get 10)) (local.get 11)) (local.get 12)) (local.get 13)) (local.get 14)) (local.get 15)) (local.get 16)) (local.get 17)) (local.get 18)) (local.get 19)) (local.get 20)) (local.get 21)) (local.get 22)) (local.get 23)) (local.get 24)))
  (func $live8d (export "live8d") (param $a f64) (result f64)
    (local f64 f64 f64 f64 f64 f64 f64 f64)
    (local.set 1 (f64.mul (local.get 0) (f64.const 1.5)))
    (local.set 2 (f64.mul (local.get 0) (f64.const 2.5)))
    (local.set 3 (f64.mul (local.get 0) (f64.const 3.5)))
    (local.set 4 (f64.mul (local.get 0) (f64.const 4.5)))
    (local.set 5 (f64.mul (local.get 0) (f64.const 5.5)))
    (local.set 6 (f64.mul (local.get 0) (f64.const 6.5)))
    (local.set 7 (f64.mul (local.get 0) (f64.const 7.5)))
    (local.set 8 (f64.mul (local.get 0) (f64.const 8.5)))
    (f64.mul (f64.mul (f64.mul (f64.mul (f64.mul (f64.mul (f64.mul (local.get 1) (local.get 2)) (local.get 3)) (local.get 4)) (local.get 5)) (local.get 6)) (local.get 7)) (local.get 8)))
)
