@ Generated by Synth WASM Compiler
@ Using formally verified compilation from Coq
@ Target: ARM Cortex-M with VFP

@ Function: pid_error
@ PID error calculation: setpoint - measurement

.syntax unified
.thumb
.text

.global synth_pid_error
.type synth_pid_error, %function
synth_pid_error:
    @ Function prologue
    push {r4, lr}

    @ WASM function body
    vsub.f32 s0, s0, s1

    @ Function epilogue
    pop {r4, pc}
.size synth_pid_error, .-synth_pid_error