@ Generated by Synth WASM Compiler
@ Using formally verified compilation from Coq
@ Target: ARM Cortex-M with VFP

@ Function: pid_integral
@ PID integral update

.syntax unified
.thumb
.text

.global synth_pid_integral
.type synth_pid_integral, %function
synth_pid_integral:
    @ Function prologue
    push {r4, lr}

    @ WASM function body
    vmul.f32 s0, s0, s1
    vadd.f32 s0, s0, s1

    @ Function epilogue
    pop {r4, pc}
.size synth_pid_integral, .-synth_pid_integral