@ Generated by Synth WASM Compiler
@ Using formally verified compilation from Coq
@ Target: ARM Cortex-M with VFP

@ Function: pid_simple
@ Simplified PID term calculation

.syntax unified
.thumb
.text

.global synth_pid_simple
.type synth_pid_simple, %function
synth_pid_simple:
    @ Function prologue
    push {r4, lr}

    @ WASM function body
    vmul.f32 s0, s0, s1

    @ Function epilogue
    pop {r4, pc}
.size synth_pid_simple, .-synth_pid_simple