/* RISC-V Bare-Metal Startup
 * Generated by synth-backend-riscv
 * Target: RV32IMAC (16 PMP entries, FPU: false)
 */

#include <stdint.h>

extern uint32_t _stack_top;
extern uint32_t __global_pointer$;
extern uint32_t __linear_memory_base;
extern uint32_t _data_start, _data_end, _data_load;
extern uint32_t _bss_start, _bss_end;
extern int main(void);

/* Default trap handler — overridable by user code. */
__attribute__((weak)) void synth_trap_handler(
    uint32_t mcause, uint32_t mepc, uint32_t mtval) {
    (void)mcause; (void)mepc; (void)mtval;
    /* Default: spin so debuggers can inspect the fault. */
    while (1) { __asm__ volatile("wfi"); }
}

__attribute__((naked, noreturn, section(".text._reset")))
void _reset(void) {
    __asm__ volatile(
        /* Disable interrupts during boot. */
        "csrw mie, zero\n"
        "csrw mip, zero\n"

        /* Initialize sp, gp, and the wasm linear-memory base. */
        ".option push\n"
        ".option norelax\n"
        "la sp, _stack_top\n"
        "la gp, __global_pointer$\n"
        "la s11, __linear_memory_base\n"
        ".option pop\n"

        /* Install the trap vector (direct mode). */
        "la t0, _trap_entry\n"
        "csrw mtvec, t0\n"

        /* Copy .data from flash to RAM. */
        "la t0, _data_load\n"
        "la t1, _data_start\n"
        "la t2, _data_end\n"
        "1:\n"
        "bgeu t1, t2, 2f\n"
        "lw t3, 0(t0)\n"
        "sw t3, 0(t1)\n"
        "addi t0, t0, 4\n"
        "addi t1, t1, 4\n"
        "j 1b\n"
        "2:\n"

        /* Zero .bss. */
        "la t0, _bss_start\n"
        "la t1, _bss_end\n"
        "3:\n"
        "bgeu t0, t1, 4f\n"
        "sw zero, 0(t0)\n"
        "addi t0, t0, 4\n"
        "j 3b\n"
        "4:\n"

        /* Jump to main. If main returns, spin. */
        "call main\n"
        "5: wfi\n"
        "j 5b\n"
    );
}

/* Trap entry — saves the caller-saved register set, marshals
 * mcause/mepc/mtval into a0/a1/a2, and dispatches to the C handler.
 */
__attribute__((naked, aligned(4), section(".text._trap_entry")))
void _trap_entry(void) {
    __asm__ volatile(
        "addi sp, sp, -64\n"
        "sw  ra,  0(sp)\n"
        "sw  t0,  4(sp)\n"
        "sw  t1,  8(sp)\n"
        "sw  t2, 12(sp)\n"
        "sw  a0, 16(sp)\n"
        "sw  a1, 20(sp)\n"
        "sw  a2, 24(sp)\n"
        "sw  a3, 28(sp)\n"
        "sw  a4, 32(sp)\n"
        "sw  a5, 36(sp)\n"
        "sw  a6, 40(sp)\n"
        "sw  a7, 44(sp)\n"
        "sw  t3, 48(sp)\n"
        "sw  t4, 52(sp)\n"
        "sw  t5, 56(sp)\n"
        "sw  t6, 60(sp)\n"

        "csrr a0, mcause\n"
        "csrr a1, mepc\n"
        "csrr a2, mtval\n"
        "call synth_trap_handler\n"

        "lw  ra,  0(sp)\n"
        "lw  t0,  4(sp)\n"
        "lw  t1,  8(sp)\n"
        "lw  t2, 12(sp)\n"
        "lw  a0, 16(sp)\n"
        "lw  a1, 20(sp)\n"
        "lw  a2, 24(sp)\n"
        "lw  a3, 28(sp)\n"
        "lw  a4, 32(sp)\n"
        "lw  a5, 36(sp)\n"
        "lw  a6, 40(sp)\n"
        "lw  a7, 44(sp)\n"
        "lw  t3, 48(sp)\n"
        "lw  t4, 52(sp)\n"
        "lw  t5, 56(sp)\n"
        "lw  t6, 60(sp)\n"
        "addi sp, sp, 64\n"
        "mret\n"
    );
}
